### ISSUE TITLE
Error on load

### ISSUE THREAD

**Issue by ipiers** [NorthernMan54/homebridge-warmup4ie#1]
I have just installed the plugin and get the following error:

```
[3/26/2020, 17:59:22] Loaded plugin: homebridge-warmup4ie
/usr/lib/node_modules/homebridge-warmup4ie/node_modules/googleapis/build/src/apis/compute/beta.js:15573
            if (typeof optionsOrCallback === 'function'9 {
                                                       ^

SyntaxError: Unexpected number
    at compileFunction (<anonymous>)
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-warmup4ie/node_modules/googleapis/build/src/apis/compute/index.js:18:16)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
```

**Comment by ipiers** [comment]
Must have been some error on install. The beta.js file was full of garbled code. I uninstalled and reinstalled and now working fine. Thanks, Dev.
