### ISSUE TITLE
issue at start 

### ISSUE THREAD

**Issue by testpaul999** [NorthernMan54/homebridge-warmup4ie#2]
Hi,
until today i get never running your Plugin.
the access to the website won't work fine, link user and PW are right.
my config:
,
        {
            "platform": "warmup4ie",
            "name": "WarmUP",
            "username": "user",
            "password": "pw-user",
            "duration": "15",
            "refresh": "45"
        }
the error meassages:

Error: _generate_access_token Error: ETIMEDOUT
    at Timeout.<anonymous> (/usr/local/lib/node_modules/homebridge-warmup4ie/node_modules/request/request.js:848:19)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: 'ETIMEDOUT',
  connect: true
}
Missing access token.
Missing LocId
[2020-4-6 8:24:57] TypeError: Cannot read property 'length' of undefined
    at warmup4iePlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-warmup4ie/index.js:63:44)
    at /usr/local/lib/node_modules/homebridge-warmup4ie/lib/warmup4ie.js:85:9
    at Warmup4IE._getRooms (/usr/local/lib/node_modules/homebridge-warmup4ie/lib/warmup4ie.js:159:5)
    at Warmup4IE.<anonymous> (/usr/local/lib/node_modules/homebridge-warmup4ie/lib/warmup4ie.js:84:17)
    at Warmup4IE._getLocations (/usr/local/lib/node_modules/homebridge-warmup4ie/lib/warmup4ie.js:337:5)
    at Warmup4IE.<anonymous> (/usr/local/lib/node_modules/homebridge-warmup4ie/lib/warmup4ie.js:83:19)
    at Request._callback (/usr/local/lib/node_modules/homebridge-warmup4ie/lib/warmup4ie.js:294:9)
    at self.callback (/usr/local/lib/node_modules/homebridge-warmup4ie/node_modules/request/request.js:185:22)
    at Request.emit (events.js:311:20)
    at Timeout.<anonymous> (/usr/local/lib/node_modules/homebridge-warmup4ie/node_modules/request/request.js:851:16)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
Uncaught exception error:  TypeError: Cannot read property 'length' of undefined
    at warmup4iePlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-warmup4ie/index.js:63:44)
    at /usr/local/lib/node_modules/homebridge-warmup4ie/lib/warmup4ie.js:85:9
    at Warmup4IE._getRooms (/usr/local/lib/node_modules/homebridge-warmup4ie/lib/warmup4ie.js:159:5)
    at Warmup4IE.<anonymous> (/usr/local/lib/node_modules/homebridge-warmup4ie/lib/warmup4ie.js:84:17)
    at Warmup4IE._getLocations (/usr/local/lib/node_modules/homebridge-warmup4ie/lib/warmup4ie.js:337:5)
    at Warmup4IE.<anonymous> (/usr/local/lib/node_modules/homebridge-warmup4ie/lib/warmup4ie.js:83:19)
    at Request._callback (/usr/local/lib/node_modules/homebridge-warmup4ie/lib/warmup4ie.js:294:9)
    at self.callback (/usr/local/lib/node_modules/homebridge-warmup4ie/node_modules/request/request.js:185:22)
    at Request.emit (events.js:311:20)
    at Timeout.<anonymous> (/usr/local/lib/node_modules/homebridge-warmup4ie/node_modules/request/request.js:851:16)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

**Comment by testpaul999** [comment]
one more trace
Error: _getRooms Error: ETIMEDOUT
    at Timeout.<anonymous> (/usr/local/lib/node_modules/homebridge-warmup4ie/node_modules/request/request.js:848:19)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: 'ETIMEDOUT',
  connect: true
}

**Comment by iliasp** [comment]
Error: _getRooms Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/homebridge/node_modules/homebridge-warmup4ie/node_modules/request/request.js:816:19)
    at Object.onceWrapper (events.js:416:28)
    at ClientRequest.emit (events.js:310:20)
    at TLSSocket.emitRequestTimeout (_http_client.js:714:9)
    at Object.onceWrapper (events.js:416:28)
    at TLSSocket.emit (events.js:310:20)
    at TLSSocket.Socket._onTimeout (net.js:479:8)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: 'ESOCKETTIMEDOUT',
  connect: false
}

I am constantly getting this from the plugin

**Comment by bsoener** [comment]
Error: _getRooms Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-warmup4ie/node_modules/request/request.js:816:19)
    at Object.onceWrapper (events.js:421:28)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.emitRequestTimeout (_http_client.js:784:9)
    at Object.onceWrapper (events.js:421:28)
    at TLSSocket.emit (events.js:327:22)
    at TLSSocket.Socket._onTimeout (net.js:483:8)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  code: 'ESOCKETTIMEDOUT',
  connect: false
}

please fix..

**Comment by ultrasnail** [comment]
Same issue for me. Has anyone come up with a workaround? Guessing NorthernMan54 is no longer supporting?

**Comment by Johcan** [comment]
Just installed this plugin on my HOOBS system running 3.3.12 firmware.

All the credentials are fine as I see in the HOOBS logs that it finds my two WarmUP 4ie panels.

Then, my HOOBS system STOPS all services with a "SIGTERM" message seen in the Logs. I can un-install this plugin and all then works fine. As soon as re-installed, same thing happens.

Any ideas?

**Comment by Jinkster1** [comment]
Will this work with the 6ie?

**Comment by Johcan** [comment]
Upgraded HOOBS to latest 4.2.5 firmware.

Tried to install "Warmup41e" plugin again and NO luck!

All I get is as follows:

20/05/2022, 15:16:31Warmup4ie BridgeLoaded plugin 'homebridge-warmup4ie'
20/05/2022, 15:16:34Warmup4ie BridgeLoading 2 platforms...
20/05/2022, 15:16:34Warmup4ie Bridgewarmup4ieLogging into warmup4ie...
20/05/2022, 15:16:35Warmup4ie BridgeERRORMissing access token.
20/05/2022, 15:16:35Warmup4ie BridgeERRORMissing LocId

I know this has been reported before.

Doesn't look like the original developer is supporting this plugin anymore?

Anyone have a fix?

**Comment by Johcan** [comment]
> Will this work with the 6ie?

This plugin doesn't work anymore running under HOOBS and using a 4ie panel!
